---
title: "Ford GoBike Data Collection & Cleaning"
author: "Alec Lepe"
date: "09/07/2018"
output: 
  html_document:
    fig_width: 6
    fig_height: 4
---
  <!-- html_document: -->
  <!--   keep_md: true -->
```{r setup, include = FALSE}
library("data.table")
library("RCurl")
library("tidyverse")
library("skimr")
library("ggplot2")
library("lubridate")
library("rjson")
#install.packages("devtools")
library("devtools")
#devtools::install_github(c("ramnathv/htmlwidgets", "rstudio/dygraphs"),force=TRUE)
library(dygraphs)
library(xts)
#knitr::opts_chunk$set(fig.width = 5, fig.asp = 1/3)
```
``` {r load}
setwd("~/Ford-GoBike/Clean Data")
load("FGB.RData")
```
``` {r total_bikeship}
x=FGB[,length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship1}
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r, fig.width=6, fig.height=2.5}
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_sf}
x=FGB[`start city`=="San Francisco" & `end city`=="San Francisco",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Intra-SF Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```

``` {r total_bikeship_oa}
x=FGB[`start city`=="Oakland" & `end city`=="Oakland",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Intra-Oakland Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_berkeley}
x=FGB[`start city`=="Berkeley" & `end city`=="Berkeley",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Intra-Berkeley Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_em}
x=FGB[`start city`=="Emeryville" & `end city`=="Emeryville",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Intra-Emeryville Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_sj}
x=FGB[`start city`=="San Jose" & `end city`=="San Jose",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Intra-San Jose Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_non_intras}
x=FGB[`start city`!=`end city`,length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("Non Intra-City Total Rides")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```


``` {r total_bikeship_sa}
x=FGB[start_daytype=="Saturday",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides (Saturdays)")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```

``` {r total_bikeship_su}
x=FGB[start_daytype=="Sunday",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides (Sundays)")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_weekends}
x=FGB[start_daytype=="Saturday" | start_daytype=="Sunday",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides (Weekends)")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```
``` {r total_bikeship_weekdays}
x=FGB[substr(start_daytype,1,1)!="S",length(bike_id),by=.(start_date)]
x[["start_date"]]=as.Date(x[["start_date"]],"%Y-%m-%d")
colnames(x)[2]="Total Rides"
x=x[order(x[["start_date"]]),]
y=xts(x,x[["start_date"]])
dygraph(y,xlab="Date",ylab=("Total Rides"),main=c("System Wide Total Rides (Weekdays)")) %>% dySeries(label="Total Rides", color="Blue") %>% dyRangeSelector()
```

