---
title: "Ford GoBike Load Data"
author: "Alec Lepe"
date: "02/12/2018"
output: 
  html_document:
    keep_md: true
---

``` {r load_base_functions,echo=FALSE,message=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,fig.height=1,figwidth=1,warnings=F)
```

``` {r library, include=F,echo=F}
library("lubridate");library("reshape");library("data.table");library("RCurl");library("tidyverse");library("skimr");library("ggplot2");library("lubridate");library("rjson")
knitr::opts_chunk$set(fig.width = 1, fig.length=1, fig.asp = 1,  message=FALSE)
```

``` {r HelperFunctions}
cc=function(x,y=" "){
  strsplit(as.character(x),split=y)[[1]]
}

ann=function(x){
  if (is.matrix(x)){
    for (i in seq(1,ncol(x))){
      #z=all(as.numeric(unique(x[,i]))==unique(x[[i]]))
      z=all(as.numeric(unique(x[,i]))==unlist(lapply(lapply(strsplit(unique(x[,i]),""),function(x) x[x!="" & x!=" "]),function(x)paste(x,collapse=""))))
      if(!is.na(z) | sum(is.na(as.numeric(x[,i])))==0){
        if (z){
          mode(x[,i])='numeric'
        }
      }
    }
  } else {
    for (i in seq(1,ncol(x))){
      #        print(i)
      z=all(as.numeric(unique(x[[i]]))==unlist(lapply(lapply(strsplit(as.character(unique(x[[i]])),""),function(x) x[x!="" & x!=" "]),function(x)paste(x,collapse=""))))
      #        z=z | all(as.numeric(as.character(x[[i]]))==as.numeric(as.character(x[[i]])))
      if (!is.na(z)){
        yz="0 " %in% x[[i]] | " 0" %in% x[[i]]
        if (sum(is.na(as.numeric(x[[i]])))==0 | z | yz){
          if (!(colnames(x)[i] %in% c("Ticket","action","VAR1","Ticket_SN","Smart_Card_SN"))){
            mode(x[[i]])='numeric'
          }
        } 
        
      }
    }
  }
  return(x)
}
GenMatrix=function(cns,name){
  y=matrix(ncol=length(cns),nrow=0)
  colnames(y)=cns
  assign(paste(name),y,envir=.GlobalEnv)
}
```

### Load Data
``` {r load, message=F}
### Load 2017 data
setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
go=F
if (!("FGB.csv" %in% list.files()) | go){
  if (!("FGB 2017 Data.csv" %in% list.files())){
    FGB2017=fread("https://s3.amazonaws.com/fordgobike-data/2017-fordgobike-tripdata.csv")
    fwrite(FGB2017,"FGB 2017 Data.csv") 
  }
  ### Load data
  for (yrmo in c(seq(201801,201812),201901,201902)){
    #yrmo=201812
    link=paste0("https://s3.amazonaws.com/fordgobike-data/",yrmo,"-fordgobike-tripdata.csv.zip")
    zip=strsplit(link,"/")[[1]][5]
    csv=paste(strsplit(zip,"\\.")[[1]][1:2],collapse=".")
    if (!(csv %in% list.files(getwd())) & url.exists(link)){
      download.file(link, dest=zip, mode="wb") 
      unzip (zip, exdir = getwd())
      file.remove(zip)
    }
  }
  
  FGB2017=fread("FGB 2017 Data.csv")
  Jan2018=fread("201801-fordgobike-tripdata.csv") 
  Feb2018=fread("201802-fordgobike-tripdata.csv") 
  Mar2018=fread("201803-fordgobike-tripdata.csv") 
  Apr2018=fread("201804-fordgobike-tripdata.csv") 
  May2018=fread("201805-fordgobike-tripdata.csv") 
  Jun2018=fread("201806-fordgobike-tripdata.csv") 
  Jul2018=fread("201807-fordgobike-tripdata.csv") 
  Aug2018=fread("201808-fordgobike-tripdata.csv") 
  Sep2018=fread("201809-fordgobike-tripdata.csv") 
  Oct2018=fread("201810-fordgobike-tripdata.csv") 
  Nov2018=fread("201811-fordgobike-tripdata.csv") 
  Dec2018=fread("201812-fordgobike-tripdata.csv")
  Jan2019=fread("201901-fordgobike-tripdata.csv")
  Feb2019=fread("201902-fordgobike-tripdata.csv")
  #expand to include future months when available
  
  ### Combine all data into one data table.
  FGB=rbindlist(list(FGB2017,
                     Jan2018,Feb2018,Mar2018,
                     Apr2018,May2018,Jun2018,
                     Jul2018,Aug2018,Sep2018,
                     Oct2018,Nov2018,Dec2018,
                     Jan2019,Feb2019
  ),fill=T)
  rm(list=c('FGB2017',
            'Jan2018',
            'Feb2018',
            'Apr2018',
            'May2018',
            'Jun2018',
            'Jul2018',
            'Aug2018',
            'Sep2018',
            'Oct2018',
            'Nov2018',
            'Dec2018','Jan2019','Feb2019'
  ))
  #expand to include future months when available
  fwrite(FGB,"FGB.csv")
  save(FGB,file="FGB.RData")
}

setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
FGB=fread("FGB.csv")
#load("FGB.RData") #FGB
setwd("~/Desktop/Projects/Ford-GoBike/Clean Data")
#save(FGB,file="FGB.RData")
``` 

### Generate Station Library and Attach Starting and Ending Cities to FGB
``` {r}
json_file="https://gbfs.fordgobike.com/gbfs/en/station_information.json"
StationInfo=fromJSON(paste(readLines(json_file), collapse=","))
StationList=StationInfo[[3]][[1]]
#unlist(lapply(StationList,function(x) length(names(x))))
GenMatrix(names(StationList[[1]]),"y")
y=as.data.table(y)
for (i in 1:length(StationList)){
  y=rbindlist(list(y,as.data.table(StationList[[i]])),fill=T)
}
Stations=y
for (i in seq(1,ncol(Stations))){
  mode(Stations[[i]])="character"
}
Stations=ann(Stations)
setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
fwrite(as.data.table(Stations),"Stations.csv")

json_file="https://gbfs.fordgobike.com/gbfs/en/system_regions.json"
SystemRegions=fromJSON(paste(readLines(json_file), collapse=","))
x=as.vector(unlist(SystemRegions$data[[1]]))
GenMatrix(c("region_id","City"),"y")
for (i in seq(1,length(x)-1,2)){
  y=rbind(y,c(x[i],x[i+1]))
}
RegionIDs=data.table(y)
mode(RegionIDs[["region_id"]])="numeric"

mode(Stations[["region_id"]])="numeric"
Stations=merge(Stations,RegionIDs,by="region_id")
Stations=Stations[,!"eightd_station_services",with=F]
setwd("~/Desktop/Projects/Ford-GoBike/Clean Data")
fwrite(Stations,"stations.csv")

origins=as.data.table(cbind(Stations[["station_id"]],Stations[["City"]]))
colnames(origins)=c("start_station_id","start city")
origins=unique(origins)
destinations=as.data.table(cbind(Stations[["station_id"]],Stations[["City"]]))
colnames(destinations)=c("end_station_id","end city")
destinations=unique(destinations)

FGB=merge(FGB,origins,by="start_station_id",all.x=TRUE,allow.cartesian=TRUE)
FGB=merge(FGB,destinations,by="end_station_id",all.x=TRUE,allow.cartesian=TRUE)
FGB[["age"]]=as.numeric(strsplit(strsplit(as.character(now()),split=" ")[[1]][1],"-")[[1]][1])-FGB[["member_birth_year"]]
```

### Extract date data from start_time and end_time variables
``` {r}
setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
if ("FGB.RData" %in% list.files()  | go){
colnames(FGB)=cc("EndStationID StartStationID DurationSec StartTime EndTime StartStationName StartStationLatitude StartStationLongitude EndStationName EndStationLatitude EndStationLongitude BikeID UserType MemberBirthYear MemberGender BikeShareForAllTrip StartCity EndCity Age")
r=as.vector(vapply(FGB[["StartTime"]],function(x) strsplit(x," ")[[1]][1],character(1)))
r2=as.vector(vapply(FGB[["StartTime"]],function(x) strsplit(x," ")[[1]][2],character(1)))
FGB[["StartDate"]]=as.Date(r,"%Y-%m-%d")
FGB[["StartYear"]]=year(FGB[["StartDate"]])
FGB[["StartMonth"]]=month(FGB[["StartDate"]])
FGB[["StartMonthLabel"]]=lubridate::month(FGB[["StartDate"]],T)
FGB[["StartDay"]]=day(FGB[["StartDate"]])
FGB[["StartDayType"]]=as.character(lubridate::wday(FGB[["StartDate"]],T))
FGB[["StartTsec"]]=round(period_to_seconds(hms(r2)))
FGB[["StartHr"]]=hour(FGB[["StartTime"]])
FGB[["StartMin"]]=minute(FGB[["StartTime"]])
FGB[["StartSec"]]=second(FGB[["StartTime"]])

r=as.vector(vapply(FGB[["EndTime"]],function(x) strsplit(x," ")[[1]][1],character(1)))
r2=as.vector(vapply(FGB[["EndTime"]],function(x) strsplit(x," ")[[1]][2],character(1)))
FGB[["EndDate"]]=as.Date(r,"%Y-%m-%d")
FGB[["EndYear"]]=year(FGB[["EndDate"]])
FGB[["EndMonth"]]=month(FGB[["EndDate"]])
FGB[["EndMonthLabel"]]=lubridate::month(FGB[["EndDate"]],T)
FGB[["EndDay"]]=day(FGB[["EndDate"]])
FGB[["EndDayType"]]=as.character(lubridate::wday(FGB[["EndDate"]],T))
FGB[["EndTsec"]]=round(period_to_seconds(hms(r2)))
FGB[["EndHr"]]=hour(FGB[["EndTime"]])
FGB[["EndMin"]]=minute(FGB[["EndTime"]])
FGB[["EndSec"]]=second(FGB[["EndTime"]])

setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
save("FGB",file="FGB.RData")
}
setwd("~/Desktop/Projects/Ford-GoBike/Raw Data")
load("FGB.RData") #FGB
byv=c("StartCity","EndCity","StartDate","StartHr","StartMonthLabel","StartYear","StartDayType")
FGB[["Count"]]=1

hourly=FGB[,sum(Count),byv]
colnames(hourly)[ncol(hourly)]="Count"
hourly=hourly[!(is.na(hourly[["StartCity"]]) | is.na(hourly[["EndCity"]])),]

cities=unique(hourly[["StartCity"]])
dates=unique(hourly[["StartDate"]])
hrs=unique(hourly[["StartHr"]])
all=merge(cities,cities)
all=merge(all,as.data.table(dates))
all=merge(all,as.data.table(hrs))
all=as.data.table(all)
colnames(all)=cc("StartCity EndCity StartDate StartHr")
all=merge(all,hourly,by=colnames(all),all.x = TRUE)
all[["StartMonthLabel"]]=lubridate::month(all[["StartDate"]],T)
all[["StartYear"]]=year(all[["StartDate"]])
all[["StartDayType"]]=as.character(lubridate::wday(all[["StartDate"]],T))
all[is.na(all[["Count"]]),][["Count"]]=0
setwd("~/Desktop/Projects/Ford-GoBike/Clean Data")
fwrite(all,"Summarized FGB.csv")
save(all,file="Summarized FGB.RData")
save(FGB,file="FGB.RData")
```

