---
title: "Ford GoBike Data Visualization3"
author: "Alec Lepe"
date: "06/12/2018"
output: 
  html_document:
    keep_md: true
---

```{r setup, include = FALSE}
library("data.table")
library("RCurl")
library("tidyverse")
library("skimr")
library("ggplot2")
library("lubridate")
library("rjson")
knitr::opts_chunk$set(fig.width = 10, fig.length=10, fig.asp = 1/3,  message=FALSE)
```
### Load Data
```{r load}
setwd("~/Desktop/Projects/Ford-GoBike/Clean Data")
load("FGB.RData")
```
```{r graph5}
FGB %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) + 
  xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month")
```

```{r graph5a}
berk=FGB[FGB[["StartCity"]]=="Berkeley" & FGB[["EndCity"]]=="Berkeley",]
berk %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) +xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month\nBerkeley")
```
```{r graph5b}
sanjose=FGB[FGB[["StartCity"]]=="San Jose" & FGB[["EndCity"]]=="San Jose",]
sanjose %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) +xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month\nSan Jose")
```
```{r graph5c}
Oakland=FGB[FGB[["StartCity"]]=="Oakland" & FGB[["EndCity"]]=="Oakland",]
Oakland %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) +xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month\nOakland")
```
```{r graph5d}
SF=FGB[FGB[["StartCity"]]=="San Francisco" & FGB[["EndCity"]]=="San Francisco",]
SF %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) +xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month \nSan Francisco")
```
```{r graph5e}
Emeryville=FGB[FGB[["StartCity"]]=="Emeryville" & FGB[["EndCity"]]=="Emeryville",]
Emeryville %>% ggplot(aes(x=StartMonthLabel)) + geom_bar() + facet_grid(StartYear ~ .) +xlab("Month") + scale_y_continuous(name="Count", labels = scales::comma) +
  ggtitle("Total Rides Over Time by Month \nEmeryville")
```